### PR TITLE
feat: working on manifest V3 extension

### PR DESCRIPTION
**Pull request by mandrakenet**
Did some changes on the code to be able to run with v3 extension manifest, not very good at code, but it is working as expected

### CODE REVIEW

**Comment by mandrakenet** [comment]
is there a posibility to merge this request and publish?
With manifest v3 will enable to publish new version on Chorme web store
Also added feature to change footer color to the same color selected for header @yaggytter

**Comment by mandrakenet** [comment]
Also added feature to change footer color to the same color selected for header

**Comment by yaggytter** [comment]
Thank you for your contribution. I will check it as soon as possible.

**Review by yaggytter — APPROVED** [review]
LGTM! Thank you!

**Comment by yaggytter** [comment]
I merge it before fixing current issue https://github.com/yaggytter/chrome-extension-awssso/issues/16 .

**Pull request merged**
